[package]
name = "plot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.152"
serde_json = "1.0.93"
plotters = { version = "0.3.4", default_features = false, features = ["svg_backend", "line_series"] }
calc_lib = "2.1.0"
base64 = "0.21.0"