[workspace]
members = [
    "cli",
    "core",
    "parser",
    "module-tests"
]

exclude = ["packages/table", "packages/html", "playground/web_bindings"]

# We need to specifiy that we use the new resolver to
# get wasmer to build correctly when using a workspace
# for some reason
resolver = "2"
