[workspace]
members = [
    "cli",
    "core",
    "parser",
]

exclude = ["modules/test-module", "modules/table", "playground/web_bindings"]

# We need to specifiy that we use the new resolver to
# get wasmer to build correctly when using a workspace
# for some reason
resolver = "2"
