[workspace]
members = [
    "cli",
    "core",
    "parser",
    "playground/web_bindings",
]

exclude = ["modules/test-module"]

# We need to specifiy that we use the new resolver to
# get wasmer to build correctly when using a workspace
# for some reason
resolver = "2"
