[package]
name = "bibliography"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.152", features = ["derive"]}
serde_json = "1.0.93"
# Use git-dependency for now, since we need the abbreviate_journals field added in my PR at typst/hayagriva#45, which
# isn't in a release yet
hayagriva = {git = "https://github.com/typst/hayagriva"}
