/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function is_ready_for_recompile(): number;
export function ast(a: number, b: number, c: number): void;
export function ast_debug(a: number, b: number, c: number): void;
export function transpile(a: number, b: number, c: number, d: number, e: number): void;
export function transpile_no_document(a: number, b: number, c: number, d: number, e: number): void;
export function json_output(a: number, b: number, c: number): void;
export function configure_from_source(a: number, b: number, c: number): void;
export function package_info(a: number): void;
export function get_file_list(a: number, b: number, c: number): void;
export function add_file(a: number, b: number, c: number, d: number, e: number): void;
export function add_folder(a: number, b: number, c: number): void;
export function rename_entry(a: number, b: number, c: number, d: number, e: number): void;
export function remove_file(a: number, b: number, c: number): void;
export function remove_folder(a: number, b: number, c: number): void;
export function read_file(a: number, b: number, c: number): void;
export function get_req_left(): number;
export function blank_context(): void;
export function canonical_abi_realloc(a: number, b: number, c: number, d: number): number;
export function canonical_abi_free(a: number, b: number, c: number): void;
export function __wbg_wasmerruntimeerror_free(a: number): void;
export function wasmerruntimeerror___wbgd_downcast_token(): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h840b30b8ac5a1b41(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
