[package]
name = "package-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
datatest-stable = "0.1.3"
serde = "1.0.152"
serde_json = "1.0.93"
diffy = "0.3.0"

[[test]]
name = "package_tests"
harness = false
