# This is a workflow based on an example provided by GitHub and on rossjrw/pr-preview-action
name: Deploy Playground Preview

on:
  # Runs on pushes targeting the default branch
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write
  pull-requests: write

# Allow one concurrent deployment
concurrency:
  group: "preview-${{ github.event.number }}"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./playground
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup output directory
        run: mkdir build
      - name: Install toolchain (minimal, stable, wasm32-unknown-unknown + wasm32-wasi)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown, wasm32-wasi
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Make build script executable
        run: chmod +x ./build-playground.sh
      - name: Build Playground
        run: ./build-playground.sh
      - name: Remove auto-generated .gitignore
        run: rm build/pkg/.gitignore
      - name: Copy deployment files
        run: |
          mkdir site-deploy
          cp -r build/* site-deploy
      - name: Print generated files
        run: ls -R site-deploy
      - name: Deploy Playground preview
        uses: rossjrw/pr-preview-action@v1
        with:
          custom-url: modmark.org
          source-dir: ./playground/site-deploy/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: deploy
  teardown:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Teardown Playground preview
        uses: rossjrw/pr-preview-action@v1
        with:
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: remove
